### ISSUE TITLE
Deployment instructions for hogwarts

### ISSUE THREAD

**Issue by danacr** [PAIR-code/federated-learning#40]
When trying to deploy the hogwarts demo using Docker, it fails to build. Is there any specific command you require?

**Comment by asross** [comment]
So, there are potentially several problems -- the first is that you might not have a `.yalc` folder until you've locally run `yarn`, and the second is that you might not have passed all the arguments required for Docker (see the Dockerfile for more details). Could you provide any more details, and are you able to run the app locally?

**Comment by danacr** [comment]
I don't have the Mac os machine with me. Is there any way to contact you? I tried gitter, but I don't think you're using it.

**Comment by asross** [comment]
I think maybe it would be easiest to wait until you have access to a mac or linux machine. The app should work through Docker, but for now I'm afraid it's still going to require local setup.

Also, you should know that this is a very experimental repository, and it's actually been developed as part of an internship that's ending today. So I'm not sure if I'm prepared to provide that kind of support :sweat_smile: But I very much appreciate your interest!

**Comment by danacr** [comment]
Haha, that is sad to hear. Me and a colleague of mine are working on an academic paper on decentralized federated learning and were planning to try using your repo for the first test. Nothing production facing.

**Comment by danacr** [comment]
The error slightly confuses me, this is the output from Docker run
`2018-08-17 16:43:42.057236: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
fs.js:119
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:337:20)
    at Object.readFileSync (fs.js:374:19)
    at Object.<anonymous> (/app/demo/audio/server/server.js:65:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by asross** [comment]
So, looking at [line 65 of `server.js`](https://github.com/PAIR-code/federated-learning/blob/c8a9347f70266022f2292aafeefd2cf31b5a09a3/demo/audio/server/server.js#L65), it seems like the problem is that you passed `SSL_KEY` as an environment variable but it didn't actually point to a file that got transferred over to the Docker container. In the version I deployed, I kept the SSL key/cert in `demo/audio/server/secrets/`, which is `.gitignore`d. So I would try copying your key/cert there (or `ADD`ing the directory where they're stored to the container).

**Comment by asross** [comment]
You also don't _have_ to pass `SSL_KEY` / `SSL_CERT` in as environment variables; but if you don't, then the library will only work over HTTP, which isn't ideal for a framework motivated by privacy concerns :) Also, if you're not on localhost, chrome won't give you access to the webcam without it!

**Comment by danacr** [comment]
I fixed that part, now i'm getting this one: 
` /Users/danacristinii/federated-learning/demo/audio/client/index.js: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/danacristinii/federated-learning/demo/audio/client"
    at /usr/local/lib/node_modules/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/parcel/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/parcel/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.getParserOptions (/usr/local/lib/node_modules/parcel/src/assets/JSAsset.js:74:20)
error Command failed with exit code 1.
`
