### ISSUE TITLE
Error Hogwarts Demo

### ISSUE THREAD

**Issue by setsometso** [PAIR-code/federated-learning#42]
Hi there, i cant start the hogwarts Demo. I am using mac os.

> REQ4910:server u719611$ yarn && yarn dev
> yarn install v1.9.4
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> [1/4] 🔍  Resolving packages...
> success Already up-to-date.
> $ ./postinstall.sh
> yarn run v1.9.4
> $ rm -rf dist/ && yarn && yarn build && yalc publish
> [1/4] 🔍  Resolving packages...
> success Already up-to-date.
> $ tsc
> federated-learning-server@0.0.5-d8a88bae published in store.
> ✨  Done in 3.97s.
> federated-learning-server@0.0.5-d8a88bae linked ==> /Users/u719611/Documents/Federated-Learning/federated-learning-master-tensorflowjs/demo/audio/server/node_modules/federated-learning-server
> yarn run v1.9.4
> $ yarn postinstall && cross-env NODE_ENV=production parcel build index.html results.html --no-minify --public-url ./
> $ ./postinstall.sh
> $ rm -rf dist/ && yarn && yarn build && yalc publish
> [1/4] 🔍  Resolving packages...
> success Already up-to-date.
> $ tsc
> federated-learning-client@0.0.5-26e325e7 published in store.
> federated-learning-client@0.0.5-26e325e7 linked ==> /Users/u719611/Documents/Federated-Learning/federated-learning-master-tensorflowjs/demo/audio/client/node_modules/federated-learning-client
> events.js:167
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn parcel ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
>     at onErrorNT (internal/child_process.js:407:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
>     at startup (internal/bootstrap/node.js:279:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
> Emitted 'error' event at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
>     at onErrorNT (internal/child_process.js:407:16)
>     [... lines matching original stack trace ...]
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> cp: dist/*: No such file or directory
> ✨  Done in 9.83s.
> yarn run v1.9.4
> $ yarn postinstall && node server.js
> $ ./postinstall.sh
> $ rm -rf dist/ && yarn && yarn build && yalc publish
> [1/4] 🔍  Resolving packages...
> success Already up-to-date.
> $ tsc
> federated-learning-server@0.0.5-d8a88bae published in store.
> federated-learning-server@0.0.5-d8a88bae linked ==> /Users/u719611/Documents/Federated-Learning/federated-learning-master-tensorflowjs/demo/audio/server/node_modules/federated-learning-server
> $ yarn postinstall && cross-env NODE_ENV=production parcel build index.html results.html --no-minify --public-url ./
> $ ./postinstall.sh
> $ rm -rf dist/ && yarn && yarn build && yalc publish
> [1/4] 🔍  Resolving packages...
> success Already up-to-date.
> $ tsc
> federated-learning-client@0.0.5-26e325e7 published in store.
> federated-learning-client@0.0.5-26e325e7 linked ==> /Users/u719611/Documents/Federated-Learning/federated-learning-master-tensorflowjs/demo/audio/client/node_modules/federated-learning-client
> events.js:167
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn parcel ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
>     at onErrorNT (internal/child_process.js:407:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
>     at startup (internal/bootstrap/node.js:279:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
> Emitted 'error' event at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
>     at onErrorNT (internal/child_process.js:407:16)
>     [... lines matching original stack trace ...]
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> cp: dist/*: No such file or directory
> 2018-09-10 15:23:10.801166: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
> internal/modules/cjs/loader.js:583
>     throw err;
>     ^
> 
> Error: Cannot find module 'node-fetch'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/Users/u719611/Documents/Federated-Learning/federated-learning-master-tensorflowjs/demo/audio/server/.yalc/federated-learning-server/dist/fetch_polyfill.js:3:20)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by anupamme** [comment]
Hello @setsometso I am also running into this error.

Were you able to resolve this?

**Comment by setsometso** [comment]
Nope... @anupamme

**Comment by anupamme** [comment]
@setsometso  I could resolve this error by upgrading the version of yarn to 1.12.3
