### ISSUE TITLE
Error in Emoji hunt demo

### ISSUE THREAD

**Issue by vishwajit123** [PAIR-code/federated-learning#43]
I get the following error when I run `yarn dev` to setup the federated server

`RangeError: Invalid typed array length: 424424
    at new Float32Array (<anonymous>)
    at /home/psi/flp/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:391:19
    at Array.map (<anonymous>)
    at flatDeserialize (/home/psi/flp/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:388:24)
    at FederatedServerDynamicModel.<anonymous> (/home/psi/flp/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:334:36)
    at step (/home/psi/flp/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:42:23)
    at Object.next (/home/psi/flp/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:23:53)
    at fulfilled (/home/psi/flp/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:14:58)`

Here is the snippet that the error points to: 
381: exports.flatSerialize = flatSerialize;
382:      function flatDeserialize(_a) {
             var data = _a.data, _b = _a.json, meta = _b.meta, byteOffsets = _b.byteOffsets;
             var numels = meta.map(function (_a) {
             var shape = _a.shape;
             return shape.reduce(function (x, y) { return x * y; }, 1);
          });
        var tensors = meta.map(function (_a, i) {
        var shape = _a.shape, dtype = _a.dtype;
        var ctor = common_1.dtypeToTypedArrayCtor[dtype];
        var arr = new ctor(data.buffer, byteOffsets[i], numels[i]);
        return tf.tensor(arr, shape, dtype);
        });
        return tensors;
395: }

**Comment by raghu20ram** [comment]
hi @vishwajit123 how did you run the demo , I am facing issues while running the demo?
