### ISSUE TITLE
RangeError: Invalid typed array length: 216

### ISSUE THREAD

**Issue by loretoparisi** [PAIR-code/federated-learning#44]
I get this error after running `yarn dev`:

```
$ yarn postinstall && ./deploy.sh
$ ./postinstall.sh
$ rm -rf dist/ && yarn && yarn build && yalc publish
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ tsc
federated-learning-server@0.0.5-d8a88bae published in store.
$ yarn postinstall && parcel build index.html
$ ./postinstall.sh
$ rm -rf dist/ && yarn && yarn build && yalc publish
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ tsc
federated-learning-client@0.0.5-26e325e7 published in store.
federated-learning-client@0.0.5-26e325e7 linked ==> /Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/client/node_modules/federated-learning-client
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["babel-core@^6.26.3"] is trying to unpack in the same destination "/Users/loretoparisi/Library/Caches/Yarn/v1/npm-babel-core-6.26.3-b2e2f09e342d0f0c88e2f02e067794125e75c207" as pattern ["babel-core@^6.25.0","babel-core@^6.26.0"]. This could result in non-deterministic behavior, skipping.
[3/4] Linking dependencies...
warning " > @tensorflow/tfjs-converter@0.5.2" has unmet peer dependency "@tensorflow/tfjs-core@~0.12.4".
error An unexpected error occurred: "Reduce of empty array with no initial value".
info If you think this is a bug, please open a bug report with the information provided in "/Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/client/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
🚨  /Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/client/index.html: Failed to install babel-core.
    at PromiseQueue.install [as process] (/usr/local/lib/node_modules/parcel/src/utils/installPackage.js:46:11)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
federated-learning-server@0.0.5-d8a88bae linked ==> /Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/server/node_modules/federated-learning-server
error Command "parcel" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2018-10-22 18:56:52.407559: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
1
(node:74723) Warning: N-API is an experimental feature and could change at any time.
RangeError: Invalid typed array length: 216
    at typedArrayConstructByArrayBuffer (<anonymous>)
    at new Float32Array (native)
    at /Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:391:19
    at Array.map (<anonymous>)
    at flatDeserialize (/Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:388:24)
    at FederatedServerDynamicModel.<anonymous> (/Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:334:36)
    at step (/Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:42:23)
    at Object.next (/Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:23:53)
    at fulfilled (/Users/loretoparisi/Documents/Projects/AI/federated-learning/demo/emoji_hunt/server/.yalc/federated-learning-server/dist/models.js:14:58)
    at <anonymous>
✨  Done in 21.70s.
```

**Comment by anupamme** [comment]
@loretoparisi were you able to resolve this error? I am also getting same error.

**Comment by anupamme** [comment]
@loretoparisi I was able to resolve this by upgrading the version of yarn to 1.12.3.
