### ISSUE TITLE
Error when installing emoji server

### ISSUE THREAD

**Issue by VatsaPatel** [PAIR-code/federated-learning#47]
common.ts:103:16 - error TS7017: Element implicitly has an 'any' type because type '{ 'float32': Float32ArrayConstructor; 'int32': Int32ArrayConstructor; 'bool': Uint8ArrayConstruct...' has no index signature.

103   const ctor = dtypeToTypedArrayCtor[dtype];
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


models.ts:227:3 - error TS2322: Type '{ data: Uint8Array; json: { meta: { shape: number[] | [number, number] | [number, number, number,...' is not assignable to type 'FlatVars'.
  Types of property 'json' are incompatible.
    Type '{ meta: { shape: number[] | [number, number] | [number, number, number, number] | [number, number...' is not assignable to type '{ meta: { shape: number[]; dtype: "float32" | "int32" | "bool"; }[]; byteOffsets: number[]; }'.
      Types of property 'meta' are incompatible.
        Type '{ shape: number[] | [number, number] | [number, number, number, number] | [number, number, number...' is not assignable to type '{ shape: number[]; dtype: "float32" | "int32" | "bool"; }[]'.
          Type '{ shape: number[] | [number, number] | [number, number, number, number] | [number, number, number...' is not assignable to type '{ shape: number[]; dtype: "float32" | "int32" | "bool"; }'.
            Types of property 'dtype' are incompatible.
              Type '"float32" | "int32" | "bool" | "complex64"' is not assignable to type '"float32" | "int32" | "bool"'.
                Type '"complex64"' is not assignable to type '"float32" | "int32" | "bool"'.

227   return {data: dataArr, json: {meta, byteOffsets}};
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@tensorflow/tfjs-core/dist/kernels/webgl/gpgpu_context.d.ts:15:27 - error TS2304: Cannot find name 'WebGLLoseContext'.

15     loseContextExtension: WebGLLoseContext;
                             ~~~~~~~~~~~~~~~~


error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ yarn postinstall && parcel build index.html
$ ./postinstall.sh
$ rm -rf dist/ && yarn && yarn build && yalc publish
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ tsc
federated-learning-client@0.0.5-1634489f published in store.
federated-learning-client@0.0.5-1634489f linked ==> /Users/vatsa/Desktop/Proj/federated-learning-master/demo/emoji_hunt/client/node_modules/federated-learning-client
/bin/sh: parcel: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
federated-learning-server@0.0.5-d8a88bae linked ==> /Users/vatsa/Desktop/Proj/federated-learning-master/demo/emoji_hunt/server/node_modules/federated-learning-server
error Command "parcel" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (/Users/vatsa/Desktop/Proj/federated-learning-master/demo/emoji_hunt/server/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:7:9)
    at /Users/vatsa/Desktop/Proj/federated-learning-master/demo/emoji_hunt/server/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:53:5
    at Object.<anonymous> (/Users/vatsa/Desktop/Proj/federated-learning-master/demo/emoji_hunt/server/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:1100:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.nodeDevHook [as .js] (/Users/vatsa/Desktop/Proj/federated-learning-master/demo/emoji_hunt/server/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[ERROR] 03:37:32 TypeError: Object prototype may only be an Object or null: undefined

**Comment by nsthorat** [comment]
Here is a PR to update the docs (which I ran and everything compiled just file): https://github.com/PAIR-code/federated-learning/pull/48

If these instructinos don't work, would you mind posting the commands to repro?
